name: gutenberg

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    command: ["--default-authentication-plugin=mysql_native_password"]
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u$${MYSQL_USER} -p$${MYSQL_PASSWORD} || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
      args:
        WORDPRESS_VERSION: "6.6"
        PHP_TAG: php8.2-fpm
    image: wp_php:6.6-php8.2-fpm
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      XDEBUG_MODE: ${XDEBUG_MODE}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - wp_data:/var/www/html
      - ./wp-content:/var/www/html/wp-content

  nginx:
    image: nginx:stable
    restart: unless-stopped
    depends_on:
      php:
        condition: service_started
    ports:
      - "8080:80"
    volumes:
      - wp_data:/var/www/html
      - ./wp-content:/var/www/html/wp-content
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  wpcli:
    image: wordpress:cli
    depends_on:
      php:
        condition: service_started
      db:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    user: "33:33"
    volumes:
      - wp_data:/var/www/html
      - ./wp-content:/var/www/html/wp-content

volumes:
  db_data:
  wp_data:
