version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -proot || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30

  php:
    build:
      context: ./php
      args:
        WORDPRESS_VERSION: 6.6.2
        PHP_TAG: php8.2-fpm
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wp
    volumes:
      - wp_core:/var/www/html
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
      - ./wp-content/mu-plugins:/var/www/html/wp-content/mu-plugins
    depends_on:
      db:
        condition: service_healthy

  wpcli:
    image: wordpress:cli-php8.2
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wp
    user: "33:33"
    working_dir: /var/www/html
    volumes:
      - wp_core:/var/www/html
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
      - ./wp-content/mu-plugins:/var/www/html/wp-content/mu-plugins
      - ./scripts:/scripts
    depends_on:
      db:
        condition: service_healthy
      php:
        condition: service_started

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - wp_core:/var/www/html:ro
      - ./wp-content:/var/www/html/wp-content:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      php:
        condition: service_started

volumes:
  db_data:
  wp_core:
